export const ADD_POST = 'ADD_POST';

export const GET_POSTS = 'GET_POSTS';

export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';

export const GET_POSTS_FAILURE = 'GET_POSTS_FAILURE';

// For a Single Post
export const GET_SINGLE_POST = 'GET_SINGLE_POST';

export const GET_SINGLE_POST_SUCCESS = 'GET_SINGLE_POST_SUCCESS';

export const GET_SINGLE_POST_FAILURE = 'GET_SINGLE_POST_FAILURE';
